# Интервал между отчетами об уровне заряда батареи измеряется в секундах
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# Добавьте защиту от сотрясения клавиатуры??
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
# Увеличьте мощность передачи BLE-радиоприемника клавиатуры, чтобы решить проблемы задержки и плохой связи слева и справа.
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Измените отображаемое имя клавиатуры по умолчанию.
CONFIG_ZMK_KEYBOARD_NAME="RePlz Lily58"
# Используется для устранения ошибок, связанных с отчетами о состоянии батареи в Windows
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# конфигурация, связанная с OLED
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
# Включить виджет для отображения количества слов в минуту
CONFIG_ZMK_WIDGET_WPM_STATUS=n
CONFIG_ZMK_WIDGET_LAYER_STATUS=n
CONFIG_ZMK_WIDGET_PERIPHERAL_STATUS=n
# Анимация кота Бонго, стучащего по клавиатуре
CONFIG_ZMK_WIDGET_BONGO_CAT=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

#Конфигурация, связанная со сном
# Миллисекунды бездействия перед переходом в режим ожидания (10 минут)
CONFIG_ZMK_IDLE_TIMEOUT=600000
# Включить поддержку глубокого сна
CONFIG_ZMK_SLEEP=y
# Миллисекунды бездействия перед погружением в глубокий сон (15 минут)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Rонфигурация ZMK-Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# Конфигурация с rgb
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Выключите RGB, когда клавиатура перейдет в режим ожидания.
CONFIG_ZMK_BACKLIGHT_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=3
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=60
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
